In [66]:
import requests
import tensorflow as tf
import numpy as np
import json
import pandas as pd

In [67]:
df = pd.read_csv(r'C:\Users\bisto\tfx-dicoding\misaelricardo-dicoding-submission\data\winequality-red-comma.csv')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [69]:
data_to_predict = df.iloc[0, :-1]
data_to_predict
test_data = data_to_predict.to_dict()

In [76]:
data = json.dumps({"instances": [test_data]})
print(data)

{"instances": [{"fixed acidity": 7.4, "volatile acidity": 0.7, "citric acid": 0.0, "residual sugar": 1.9, "chlorides": 0.076, "free sulfur dioxide": 11.0, "total sulfur dioxide": 34.0, "density": 0.9978, "pH": 3.51, "sulphates": 0.56, "alcohol": 9.4}]}

In [79]:
response = requests.post("http://localhost:8080/v1/models/red-wine-quality-model:predict", data=data)

In [80]:
if response.status_code == 200:
    predictions = response.json()["predictions"]
    # Assuming the prediction is a floating point number
    # We need to round it to the nearest integer
    predicted_quality = round(predictions[0][0])
    print("Predicted quality:", predicted_quality)
else:
    print("Error:", response.text)

Error: {
    "error": "Failed to process element: 0 key: fixed acidity of 'instances' list. Error: INVALID_ARGUMENT: JSON object: does not have named input: fixed acidity"
}